### ISSUE TITLE
Distributed CQEngine collection through Hazelcast

### ISSUE THREAD

**Issue by Verdoso** [Verdoso/GreenSummer#26]
[CQEngine - Collection Query Engine](https://github.com/npgall/cqengine) is a powerful library that allows one to index collections of Java objects and query them using different criteria with very fast performance. Unfortunately, it just works locally so when you have several nodes of an application, each one has to mantain its own copy of the indexes/collections, duplicating the tasks that need to be performed to do so. 

For example, if the data to be indexed is periodically read from a DB, all nodes will need to access the DB and index the nodes themselves each time. This solution does not scale too much.

Summer already uses [Hazelcast](https://hazelcast.org/) to replicate web sessions and incorporates a configuration that allows nodes to form a Hazelcast cluster based in [Consul](https://www.consul.io/), so it seems reasonable to use that to be able to "distribute" somehow the collections used by CQEngine.

**Comment by Verdoso** [comment]
Sinwe proposed a solution using a Hazelcast Set directly as data store of the collection (see [the gist](https://gist.github.com/sinwe/9a2a1229e08ec6faea7b)). That might work even though it would have to be updated for the latest changes of CQEngine as the API has changed in that area quite a bit.

On the other hand, we'd rather have local performance and use Hazelcast as a coordinator in the background, so we'll do it differently.

**Comment by OlegKuts** [comment]
Hello @Verdoso . Looking for solution using indexed CQEngine collection with Hazelcast. Could you please provide any feedback on solution proposed in gist, if it works ok. Updated code gist would be appreciated.

**Comment by Verdoso** [comment]
Hello @OlegKuts,
The class we are using for that is [ClusteredConcurrentIndexedCollection](https://github.com/Verdoso/GreenSummer/blob/master/summer-core/src/main/java/org/greeneyed/summer/util/ClusteredConcurrentIndexedCollection.java). We are using it and it's fine except when Hazelcast itself has issues, which have been plaguing us lately.

**Comment by OlegKuts** [comment]
Thanks for fast reply @Verdoso, and especially for code gist. Looks so different from 6 year old gist, no wonder I had hard time trying to apply it.

**Comment by Verdoso** [comment]
The gist you found is probably  the same I found and it was a bit different because it replaced directly the storage of CQEngine with a Hazelcast map. In my case, I'm using it as a replica and event detector, because I wanted to guarantee local speeds when retrieving elements and Hazelcast maps do not give you that.
At the beginning I tried as well to recreate it, but CQEngine internalves have changed quite a bit since the gist was written that it was like starting from scratch so...

And yes, we are using the ClusteredConcurrentIndexedCollection in production and it's working fine for, except when you have network issues because then Hazelcast has issues. We just add the indexes at the collections at creation time and we are not storing the index themselves in a Hazelcast map, so we are not experiencing those problems. In our solution, each node has its own independent collections and just the elements are (de)serialised by hazelcast when updating other nodes, so no index loss due to that.

**Comment by OlegKuts** [comment]
> except when you have network issues because then Hazelcast has issues
Have you tried using near cache for hazelcast maps? AFAIK u can store not only part of map data one node owns, but you actually can store all map data in each node in near cache. More over you can store it in Object instead of Binary. Thus you will be able to have performance as fast as regular non distributed caches. Several drawbacks of such approach are: 1)you spend much more memory to store data on each node; 2) you might be getting stale data for a while, after u have your map updated. If you are not short with your memory and you do not update data to often you should be fine.

**Comment by Verdoso** [comment]
I've used Hazelcast maps with near cache and even though the data might be local, the performance is not the same because hazelcast checks if the data has suffered any change, contacting the master owner node, when you read the value. They also have replicated maps, but they come with no guarantee because the updates are lossy though UDP.
Hence my using the Hazelcast maps as backup and communication but not the main storage.
But my problems with Hazelcast come from the fact that you might lose data in your maps if you happen to have nodes go down when the data is being redistributed due to a new node going up, for example.

**Comment by OlegKuts** [comment]
@Verdoso 

> Hence my using the Hazelcast maps as backup and communication but not the main storage.
Took me some time to understand it. Your use of map is only to synchronize data across nodes in CQEngine store, right?

Looks like you have much more experience with hazelcast than me. Not sure if I get you right, or maybe it was me unclear. When I do store my **whole** map in near cache on each node, de-serialized, I did not notice any network roundtrip. I am literary able to retrieve whole map from hazelcast in 0-1 milliseconds.  My near cache is configured to invalidate on change only.

> But my problems with Hazelcast come from the fact that you might lose data in your maps if you happen to have nodes go down when the data is being redistributed due to a new node going up, for example.
Haven't faced it in my use case.

**Comment by Verdoso** [comment]
@OlegKuts 

> Took me some time to understand it. Your use of map is only to synchronize data across nodes in CQEngine store, right?

Correct.

> Looks like you have much more experience with hazelcast than me. Not sure if I get you right, or maybe it was me unclear. When I do store my **whole** map in near cache on each node, de-serialized, I did not notice any network roundtrip. I am literary able to retrieve whole map from hazelcast in 0-1 milliseconds. My near cache is configured to invalidate on change only.

They might have changed it or I might have something misconfigured, but when I tested it, even when you had nearCache configured, upon access you would get a call a remote call to master to verify that nothing had changed. Hazelcast was fast, yes, but when we changed to simply local, it was even faster. And seeing that replacing the CQEngine store with hazelcast was way more complicated, I opted for this solution.

> Haven't faced it in my use case.
Lucky you :). We do rolling upgrades, so we stop node 1, 2-3 now divide the cache, start 1, now 1-2-3 start re-distributing cache again, you then stop 2. If for some reason, network delay for example, the redistribution has not finished before you stop 2, you might lose some of the data in your map. That was admited by Hazelcast and asumed as "that's how clusters work" but was later supposedly fixed. I'm still sometimes having issues after rolling upgrades when the network has isssues, but I have yet to find the real problem. It's hard to reproduce, so...

**Comment by Verdoso** [comment]
Just FYI, we have stopped using this feature when cqengine collections get too big because Hazelcast replication is too slow for the upgrade cycle so we end up losing data due to the full cluster being restarted before they have redistributed all the data again.
:'(

**Comment by OlegKuts** [comment]
Thanks for letting know. Issue was due to rolling updates, and need to stop some nodes, right?

**Comment by Verdoso** [comment]
Yes, when the Hazelcast "rearrangement" takes too long, then either you have to wait way too much or you kill all the nodes once before they have rearranged everything, so you end up losing some random part of the distributed map.

I tried making sure the number of backups was enough to have everything in all the nodes: no joy. I tried to make the updates async so it did not take that long: no joy.
The problem for me is that "most" of the times everything goes fine, the more data you hold, the more likely something is lost, and trying to fix it by re-checking all the data on startup took almost longer than reloading the data from scratch...

We are now using a polling mechanism that checks if there's been any change in the cache, stored compressed as a big blob in a repo, and if it's necessary, reloading it from the repo. Our data does not change very often, so that's more than enough. In our case, the data does not change very often and it's loaded in bulk, so reloading individual elements when the cache is empty is not an option. 

We are using Hazelcast+CQEngine in some other apps that use way less data, but we'll probably deprecate it and end up replacing it.
Cheers
