### ISSUE TITLE
Spring boot cannot start after adding summer dependency

### ISSUE THREAD

**Issue by Jerry4013** [Verdoso/GreenSummer#61]
<dependency>
            <groupId>org.greeneyed</groupId>
            <artifactId>summer</artifactId>
            <version>0.10.7</version>
        </dependency>

**Comment by Verdoso** [comment]
I would need a bit more info than that :). Have you tried latest (0.10.9)? What's the error you are getting?

**Comment by Jerry4013** [comment]
@Verdoso yes, I tried, but did not work.
This is my pom file.
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.5.RELEASE</version>
        <relativePath/> 
    </parent>
    <groupId>soen487.a2</groupId>
    <artifactId>library2</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>library2</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.greeneyed</groupId>
            <artifactId>summer</artifactId>
            <version>0.10.9</version>
        </dependency>

        <dependency>
            <groupId>net.sf.saxon</groupId>
            <artifactId>Saxon-HE</artifactId>
            <version>9.9.1-4</version>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

This is the error. My app cannot start no matter I @Enablesummer or not
15:22:31.655 [main] DEBUG org.springframework.boot.context.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: [file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/charsets.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/deploy.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/dnsns.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/jaccess.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/jfxrt.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/localedata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/nashorn.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/sunec.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/sunjce_provider.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/sunmscapi.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/sunpkcs11.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/ext/zipfs.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/javaws.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/jce.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/jfr.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/jfxswt.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/jsse.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/management-agent.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/plugin.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/resources.jar, file:/C:/Program%20Files/Java/jdk1.8.0_231/jre/lib/rt.jar, file:/C:/Concordia%20Code/soen487/a2/library2/target/classes/, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-starter-data-jpa/2.2.5.RELEASE/spring-boot-starter-data-jpa-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-starter-aop/2.2.5.RELEASE/spring-boot-starter-aop-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-aop/5.2.4.RELEASE/spring-aop-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/aspectj/aspectjweaver/1.9.5/aspectjweaver-1.9.5.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/2.2.5.RELEASE/spring-boot-starter-jdbc-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/com/zaxxer/HikariCP/3.4.2/HikariCP-3.4.2.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-jdbc/5.2.4.RELEASE/spring-jdbc-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.2/jakarta.activation-api-1.2.2.jar, file:/C:/Users/jerry/.m2/repository/jakarta/persistence/jakarta.persistence-api/2.2.3/jakarta.persistence-api-2.2.3.jar, file:/C:/Users/jerry/.m2/repository/jakarta/transaction/jakarta.transaction-api/1.3.3/jakarta.transaction-api-1.3.3.jar, file:/C:/Users/jerry/.m2/repository/org/hibernate/hibernate-core/5.4.12.Final/hibernate-core-5.4.12.Final.jar, file:/C:/Users/jerry/.m2/repository/org/jboss/logging/jboss-logging/3.4.1.Final/jboss-logging-3.4.1.Final.jar, file:/C:/Users/jerry/.m2/repository/org/javassist/javassist/3.24.0-GA/javassist-3.24.0-GA.jar, file:/C:/Users/jerry/.m2/repository/net/bytebuddy/byte-buddy/1.10.8/byte-buddy-1.10.8.jar, file:/C:/Users/jerry/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar, file:/C:/Users/jerry/.m2/repository/org/jboss/jandex/2.1.1.Final/jandex-2.1.1.Final.jar, file:/C:/Users/jerry/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar, file:/C:/Users/jerry/.m2/repository/org/dom4j/dom4j/2.1.1/dom4j-2.1.1.jar, file:/C:/Users/jerry/.m2/repository/org/hibernate/common/hibernate-commons-annotations/5.1.0.Final/hibernate-commons-annotations-5.1.0.Final.jar, file:/C:/Users/jerry/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.2/jaxb-runtime-2.3.2.jar, file:/C:/Users/jerry/.m2/repository/org/glassfish/jaxb/txw2/2.3.2/txw2-2.3.2.jar, file:/C:/Users/jerry/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.8/istack-commons-runtime-3.0.8.jar, file:/C:/Users/jerry/.m2/repository/org/jvnet/staxex/stax-ex/1.8.1/stax-ex-1.8.1.jar, file:/C:/Users/jerry/.m2/repository/com/sun/xml/fastinfoset/FastInfoset/1.2.16/FastInfoset-1.2.16.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/data/spring-data-jpa/2.2.5.RELEASE/spring-data-jpa-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/data/spring-data-commons/2.2.5.RELEASE/spring-data-commons-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-orm/5.2.4.RELEASE/spring-orm-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-context/5.2.4.RELEASE/spring-context-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-tx/5.2.4.RELEASE/spring-tx-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-beans/5.2.4.RELEASE/spring-beans-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-aspects/5.2.4.RELEASE/spring-aspects-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.2.5.RELEASE/spring-boot-starter-web-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-starter/2.2.5.RELEASE/spring-boot-starter-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot/2.2.5.RELEASE/spring-boot-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.2.5.RELEASE/spring-boot-autoconfigure-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.2.5.RELEASE/spring-boot-starter-logging-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar, file:/C:/Users/jerry/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar, file:/C:/Users/jerry/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.12.1/log4j-to-slf4j-2.12.1.jar, file:/C:/Users/jerry/.m2/repository/org/apache/logging/log4j/log4j-api/2.12.1/log4j-api-2.12.1.jar, file:/C:/Users/jerry/.m2/repository/org/slf4j/jul-to-slf4j/1.7.30/jul-to-slf4j-1.7.30.jar, file:/C:/Users/jerry/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar, file:/C:/Users/jerry/.m2/repository/org/yaml/snakeyaml/1.25/snakeyaml-1.25.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.2.5.RELEASE/spring-boot-starter-json-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.10.2/jackson-databind-2.10.2.jar, file:/C:/Users/jerry/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.10.2/jackson-annotations-2.10.2.jar, file:/C:/Users/jerry/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.10.2/jackson-core-2.10.2.jar, file:/C:/Users/jerry/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.10.2/jackson-datatype-jdk8-2.10.2.jar, file:/C:/Users/jerry/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.10.2/jackson-datatype-jsr310-2.10.2.jar, file:/C:/Users/jerry/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.10.2/jackson-module-parameter-names-2.10.2.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.2.5.RELEASE/spring-boot-starter-tomcat-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.31/tomcat-embed-core-9.0.31.jar, file:/C:/Users/jerry/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.31/tomcat-embed-el-9.0.31.jar, file:/C:/Users/jerry/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.31/tomcat-embed-websocket-9.0.31.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.2.5.RELEASE/spring-boot-starter-validation-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/jakarta/validation/jakarta.validation-api/2.0.2/jakarta.validation-api-2.0.2.jar, file:/C:/Users/jerry/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.18.Final/hibernate-validator-6.0.18.Final.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-web/5.2.4.RELEASE/spring-web-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-webmvc/5.2.4.RELEASE/spring-webmvc-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-expression/5.2.4.RELEASE/spring-expression-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/greeneyed/summer/0.10.9/summer-0.10.9.jar, file:/C:/Users/jerry/.m2/repository/org/projectlombok/lombok/1.18.12/lombok-1.18.12.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/boot/spring-boot-actuator/2.2.5.RELEASE/spring-boot-actuator-2.2.5.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/cloud/spring-cloud-context/1.2.2.RELEASE/spring-cloud-context-1.2.2.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/security/spring-security-crypto/5.2.2.RELEASE/spring-security-crypto-5.2.2.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/javax/servlet/javax.servlet-api/4.0.1/javax.servlet-api-4.0.1.jar, file:/C:/Users/jerry/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar, file:/C:/Users/jerry/.m2/repository/org/apache/commons/commons-pool2/2.7.0/commons-pool2-2.7.0.jar, file:/C:/Users/jerry/.m2/repository/net/sf/saxon/Saxon-HE/9.9.1-4/Saxon-HE-9.9.1-4.jar, file:/C:/Users/jerry/.m2/repository/org/postgresql/postgresql/42.2.10/postgresql-42.2.10.jar, file:/C:/Users/jerry/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-core/5.2.4.RELEASE/spring-core-5.2.4.RELEASE.jar, file:/C:/Users/jerry/.m2/repository/org/springframework/spring-jcl/5.2.4.RELEASE/spring-jcl-5.2.4.RELEASE.jar, file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%202019.3/lib/idea_rt.jar]
15:22:31.702 [background-preinit] DEBUG org.jboss.logging - Logging Provider: org.jboss.logging.Log4j2LoggerProvider
15:22:31.702 [background-preinit] INFO org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.18.Final
15:22:31.733 [background-preinit] DEBUG org.hibernate.validator.internal.engine.resolver.TraversableResolvers - Found javax.persistence.Persistence on classpath containing 'getPersistenceUtil'. Assuming JPA 2 environment. Trying to instantiate JPA aware TraversableResolver
15:22:31.733 [background-preinit] DEBUG org.hibernate.validator.internal.engine.resolver.TraversableResolvers - Instantiated JPA aware TraversableResolver of type org.hibernate.validator.internal.engine.resolver.JPATraversableResolver.
15:22:31.749 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
15:22:31.749 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via TCCL
15:22:31.749 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ResourceLoaderHelper - Trying to load META-INF/validation.xml via Hibernate Validator's class loader
15:22:31.749 [background-preinit] DEBUG org.hibernate.validator.internal.xml.config.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
15:22:32.005 [background-preinit] DEBUG org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator - Loaded expression factory via original TCCL
15:22:32.022 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator as ValidatorFactory-scoped message interpolator.
15:22:32.022 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.resolver.JPATraversableResolver as ValidatorFactory-scoped traversable resolver.
15:22:32.022 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.ExecutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.
15:22:32.022 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.DefaultClockProvider as ValidatorFactory-scoped clock provider.
15:22:32.022 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.
15:22:32.589 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoSuchMethodError: org.springframework.boot.builder.SpringApplicationBuilder.<init>([Ljava/lang/Object;)V
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:157)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:98)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:64)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at soen487.a2.library2.Library2Application.main(Library2Application.java:10)

Process finished with exit code 1

Thanks for your reply!

**Comment by Verdoso** [comment]
Sumer 0.10.X branch is compatible with Spring Boot 1.5.X, but not with 2.2.x.

There are many incompatibilities between Spring Boot 2.2 and 1.5 so there is no way I can make it work in both versions. Those are the bad news.

The good news are that we have an internal version that works with Spring Boot 2.2 and Java 11, with just a couple of minor features missing that we had to remove, but there is no official release yet, unfortunately. I might try to do a release if you are really interested.

**Comment by Jerry4013** [comment]
@Verdoso Thank you very much for your information! I can use Spring boot 1.5 then. Thank you for your effort!

**Comment by Verdoso** [comment]
You're welcome. Let me know if you have any issues.

We already have ~25 apps in production working with those versions and doing great. We even use some of the utilities to enable/disable them automatically from Jenkins so we can zero-downtime auto-upgrade them with some script shell wizardry.

I admit the utilies are poorly documented here, busy life, but some of the ideas behind them I describe every now and then in a blog: https://www.greeneyed.org/ and some of the techniques are already implemented in Summer (like the unique id per request or the configuring multiple ttl caches from properties).
Happy coding and don't hesitate to ask.
Cheers!
D.
