### ISSUE TITLE
Support Spring Boot 2.4.5

### ISSUE THREAD

**Issue by Haybu** [Verdoso/GreenSummer#66]
Not working with spring boot 2.4.5

**Comment by Verdoso** [comment]
No, current versión works with Spring Boot 1.5.3

We have a version  that works with Spring Boot 2.4.X but it has't been released yet. Some features had to be removed to get it to work with Spring Boot 2.4 and we upgraded JDK prerequisites to Java 11.

I'll see if I can release that version.

**Comment by Verdoso** [comment]
Fixed with release of version 0.11.4, which should appear in maven central in 24h or less

**Comment by Verdoso** [comment]
0.11.4 available at maven central
